---
title: "CyanoHABs National Drivers and Predictions"
format: docx
authors: Amalia Handler, Michael Dumelle, and Melanie Reynolds
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
# Load model development data
devtools::load_all()

# Load packages
library(here)
library(spmodel)
library(dplyr)
library(tidyr)
library(ggplot2)
library(sf)
library(tigris)
library(knitr)
library(here)
library(corrplot)
library(flextable)
library(officer)
library(officedown)

# Do not include code chunks in document
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

# Data prep
habs <- habs |>
  mutate(n_farm_inputs = N_Fert_Farm + N_CBNF + N_livestock_Waste,
         n_dev_inputs = N_Human_Waste + N_Fert_Urban,
         p_farm_inputs = P_f_fertilizer + P_livestock_Waste,
         p_dev_inputs = P_human_waste_kg + P_nf_fertilizer) |>
  mutate(MICX_DET = factor(ifelse(is.finite(MICX), 1, 0))) |>
  mutate(MAXDEPTH = ifelse(MAXDEPTH == 999, NA, MAXDEPTH),
         n_farm_inputs = ifelse(n_farm_inputs > 600, NA, n_farm_inputs),
         p_farm_inputs = ifelse(p_farm_inputs > 100, NA, p_farm_inputs),
         n_dev_inputs = ifelse(n_dev_inputs > 300, NA, n_dev_inputs),
         p_dev_inputs = ifelse(p_dev_inputs > 100, NA, p_dev_inputs),
         TEMPERATURE = ifelse(TEMPERATURE > 50, NA, TEMPERATURE))

# Load model objects
cyano_lake <- readRDS(paste0(here(), "/inst/model_objects/model_cyano_withlakedata.rds"))
micx_lake  <- readRDS(paste0(here(), "/inst/model_objects/model_micx_withlakedata.rds"))

cyano_nolake <- readRDS(paste0(here(), "/inst/model_objects/model_cyano_nolakedata.rds"))
micx_nolake  <- readRDS(paste0(here(), "/inst/model_objects/model_micx_nolakedata.rds"))

```

## Results

### Map of NLA sample locations

Note: Should this map be restricted to only the observations used in the model development?

```{r nla map compilation, message = FALSE}
# CONUS with state outlines
conus <- tigris::states(cb = TRUE, progress_bar = FALSE) |>
  filter(!STUSPS %in% c('HI', 'PR', 'AK', 'MP', 'GU', 'AS', 'VI')) |>
  st_transform(crs = 5072)

nla_map <- ggplot() + 
  geom_sf(data = conus, fill = "#e2e2e2", color = "white", size = 0.5) +
  geom_sf(data = habs, shape = 24, fill = "grey39", size = 1, stroke = .2) +
  theme_void() +
  theme(legend.position = "bottom")

```

```{r nla map}
#| label: nla-map
#| fig-width: 6
#| fig-height: 4
#| fig-cap: "Lakes sampled in the 2007, 2012, and 2017 National Lakes Assessment. Darker points represent lakes sampled multiple times."
nla_map

```

```{r setup correlation plot}
#| label: cor-plot
#| fig-width: 6
#| fig-height: 6
#| fig-cap: "Pairwise spearman's rank correlation matrix of all covariates considered for the models."

# Trim to just the variables explored in the models
cor_dat <- habs |>
  st_drop_geometry() |>
  select(TEMPERATURE, MAXDEPTH, AMMONIA_N, DOC:NITRATE_N, PH, D_EXCESS, EVAP_INFL, fst_ws, wet_ws, precip_mean_month, temp_mean_month, lakemorpho_fetch, BFIWs, KffactWs:Precip_Minus_EVTWs, Precip8110Ws, Tmean8110Ws, N_Total_Deposition, n_farm_inputs:p_dev_inputs) |>
  relocate(NTL, PTL, NITRATE_N, AMMONIA_N, DOC, PH, TEMPERATURE, TURB, D_EXCESS, EVAP_INFL, fst_ws, wet_ws, KffactWs, n_farm_inputs, p_farm_inputs, n_dev_inputs, p_dev_inputs, N_Total_Deposition, precip_mean_month, temp_mean_month, Precip8110Ws, Tmean8110Ws, Precip_Minus_EVTWs, RunoffWs, BFIWs, MAXDEPTH, lakemorpho_fetch)

var_names <- c("Total N", 
               "Total P",   
               "Nitrate", 
               "Ammonia", 
               "DOC", 
               "pH", 
               "Water Temp",
               "Turbidity",
               "Evaporation",
               "Evaporation/Inflow",
               "Forest Cover", 
               "Wetland Cover",
               "Soil Erodability",
               "Farm N Inputs",
               "Farm P Inputs",
               "Developed N Inputs", 
               "Developed P Inputs",
               "Deposition N", 
               "Monthly Precip",
               "Monthly Air Temp",
               "Annual Precip", 
               "Annual Air Temp",
               "Annual Precip-ET",
               "Runoff", 
               "Baseflow Index",
               "Lake Depth",
               "Lake Fetch")

cormat_pred <- cor(cor_dat, use = "pairwise.complete.obs", method = "spearman")

colnames(cormat_pred) <- var_names
rownames(cormat_pred) <- var_names

# Lower triangle plot
corrplot(cormat_pred, method = "ellipse", type = "lower", tl.col = "black", tl.srt = 45, tl.cex = 0.75)

```

```{r extract model fixed effects}
# Function to extract the fixed effects from each model
fixed_effect_retriever <- function(model_obj, resp_var, lake_data){
  summary(model_obj)$coefficients$fixed |>
    mutate(fixed_effect = rownames(summary(model_obj)$coefficients$fixed)) |>
    mutate(response_var = resp_var,
           lake_data = lake_data) |>
    tibble() |>
    rename(estimate = estimates) |>
    relocate(response_var, lake_data, fixed_effect, .before = estimate)
}

# Extract the effects
fixed_df <- rbind(
  fixed_effect_retriever(micx_lake, resp_var = "micx", lake_data = "present"),
  fixed_effect_retriever(micx_nolake, resp_var = "micx", lake_data = "absent"),
  fixed_effect_retriever(cyano_lake, resp_var = "cyano", lake_data = "present"),
  fixed_effect_retriever(cyano_nolake, resp_var = "cyano", lake_data = "absent")
)

# Table that includes both response variables and models with and without lake data. Covariates are converted to positive or negative signs with asterisks denoting the associated p-values.
# pal <- RColorBrewer::brewer.pal(9, "RdBu")
# pal <- c("#B2182B", "#db1d35", "#e54155", "#eb6a7a", "#F7F7F7", "#72abe4", "#4c94dd", "#287dd2", "#2166AC")
pal <- c("#eb6a7a", "#f08f9b", "#f5b4bc", "#fadade", "#F7F7F7", "#dceaf8", "#b8d5f1", "#95c0eb", "#72abe4")

est_and_sign <- fixed_df |>
  filter(!fixed_effect == "(Intercept)") |>
  mutate(est_sign = ifelse(estimate > 0, "+", "−"),
         sig = case_when(p >= 0.05 ~ "ns",
                         p < 0.05 & p >= 0.01 ~ "*",
                         p < 0.01 & p >= 0.001 ~ "**",
                         p < 0.001 ~ "***"),
         est_sig = paste0(est_sign, " (", sig, ")"),
         fixed_effect = factor(fixed_effect, 
                               levels = c("NTL",
                                          "NITRATE_N",
                                          "AMMONIA_N",
                                          "DOC",
                                          "TURB",
                                          "PH",
                                          "EVAP_INFL",
                                          "MAXDEPTH",
                                          "lakemorpho_fetch",
                                          "n_farm_inputs",
                                          "p_farm_inputs",
                                          "n_dev_inputs",
                                          "p_dev_inputs",
                                          "fst_ws",
                                          "BFIWs",
                                          "Precip8110Ws",
                                          "Tmean8110Ws",
                                          "AG_ECO3PLNLOW",
                                          "AG_ECO3EHIGH",
                                          "NTL:AG_ECO3PLNLOW",
                                          "NTL:AG_ECO3EHIGH"))
         ) |>
  select(response_var:fixed_effect, est_sig) |>
  pivot_wider(names_from = response_var:lake_data,
              values_from = est_sig,
              values_fill = "") |>
  arrange(fixed_effect) |>
  relocate(fixed_effect, cyano_present, micx_present, cyano_absent, micx_absent) |>
  mutate(fixed_effect = c("Total N",
                       "Nitrate",
                       "Ammonium",
                       "DOC",
                       "Turbidity",
                       "pH",
                       "Evaporation/Inflow",
                       "Lake Depth",
                       "Lake Fetch",
                       "Farm N Inputs",
                       "Farm P Inputs",
                       "Developed N Inputs",
                       "Developed P Inputs",
                       "Forest Cover",
                       "Baseflow Index",
                       "Annual Precip",
                       "Annual Air Temp",
                       "Ecoregion PLNLOW",
                       "Ecoregion EHIGH",
                       "Total N * PLNLOW",
                       "Total N * EHIGH"),
         Type = c(rep("In-Lake Conditions", 7),
                  rep("Lake Geometry", 2),
                  rep("Nutrient Inputs", 5),
                  rep("Geographic Setting", 5),
                  rep("Interactions", 2)), .before = fixed_effect
            ) |>
  rename(Covariates = fixed_effect)

colorer <- function(i){
  hex <- case_when(i == "+ (***)" ~ pal[1],
                   i == "+ (**)" ~  pal[2],
                   i == "+ (*)" ~   pal[3],
                   i == "+ (ns)" ~  pal[4],
                   i == "" ~        pal[5],
                   i == "− (ns)" ~  pal[6],
                   i == "− (*)" ~   pal[7],
                   i == "− (**)" ~  pal[8],
                   i == "− (***)" ~ pal[9])
}

est_header <- data.frame(
  col_keys = colnames(est_and_sign),
  line2 = c(rep("Model", 2), rep("In-Lake Conditions", 4)),
  line3 = c(rep("Model", 2), c(rep("Present", 2), rep("Absent", 2))),
  line4 = c("Type", "Corvariates", rep(c("Cyanobacteria", "Microcystin"), 2))
)

covar_tbl <- est_and_sign |>
  flextable() |>
  set_header_df(mapping = est_header, key = "col_keys" ) |>
  merge_v(part = "header", j = c(1:2)) |> 
  merge_v(part = "body", j = 1) |> 
  merge_h(part = "header", i = c(1:2)) |> 
  theme_booktabs(bold_header = TRUE) |>
  bg(bg = colorer,
     j = 3:6, # All columns in the body except for the first one
     part = "body") |>
  bg(j = c(5:6), i = c(1:7), bg = "#606060") |> # Covariates that weren't available to the models
  theme_box() |>
  align(align = "center", part = "header") |>
  fontsize(size = 10, part = "body") |>
  fontsize(size = 10, part = "header")

```

```{r covariate table}
#| label: tbl-fixed_effects
#| tbl-cap: Model fixed effect coefficient sign (negative or positive) and p-value (* <0.05, ** <0.01, **** < 0.001) for cyanobacteria and microcystin models both where in-lake data was present or absent. Grey cells are in-lake conditions covariates that were excluded from model development 
covar_tbl
```

```{r standarized residual maps}
#| label: std-resid-maps
#| fig-width: 6
#| fig-height: 6
#| fig-cap: "Standardized residuals for the cyanobacteria and microcystin models without in-lake conditions."

cyano_nolake_aug <- augment(cyano_nolake) |>
  mutate(resp = "Cyanobacteria") |>
  select(resp, .std.resid)
micx_nolake_aug  <- augment(micx_nolake) |>
  mutate(resp = "Microcystin") |>
  select(resp, .std.resid) |>
  st_transform(st_crs(cyano_nolake_aug))

std_resid_comb <- rbind(cyano_nolake_aug, micx_nolake_aug) |>
  mutate(rank = case_when(.std.resid > 4 ~ 4,
                          .std.resid > 3 & .std.resid < 4 ~ 3,
                          .std.resid < -2 ~ 2,
                          TRUE ~ 1)) |>
  arrange(rank)

ggplot() + 
  geom_sf(data = conus, fill = "#e2e2e2", color = "white", lwd = 1) +
  geom_sf(data = std_resid_comb, 
          aes(fill = .std.resid), pch = 21, size = 1.5) +
  facet_wrap(~ resp, ncol = 1, nrow = 2) +
  colorspace::scale_fill_continuous_divergingx(palette = "BrBG", 
                                               mid = 0, 
                                               name = "Standardized\nResidual") +
    theme_void()

```

```{r model fit comparison}
#| label: tbl-mod-fit
#| tbl-cap: Comparison of model fit for model where in-lake data is present or absent and based on spatial of independent error models.

comp_cyan <- readRDS(paste0(here(), "/inst/model_objects/spatial_compare_cyano.rds")) |>
  rename(fit = cor2)

comp_micx <- readRDS(paste0(here(), "/inst/model_objects/spatial_compare_micx.rds")) |>
  rename(fit = auc)

options(digits = 2)
rbind(comp_cyan, comp_micx) |>
  select(-MSPE) |>
  mutate(resp_var = case_when(resp_var == "cyano" ~ "Cyanobacteria",
                              resp_var == "micx" ~ "Microcystin"),
         lake_data = case_when(lake_data == "present" ~ "Present",
                               lake_data == "absent" ~ "Absent"),
         spatial_mod = case_when(spatial_mod == "spatial" ~ "Spatial",
                                 spatial_mod == "non-spatial" ~ "Independent")) |>
  flextable() |>
  set_header_labels(values = list(
    resp_var = "Response Variable",
    lake_data = "In-Lake Conditions",
    spatial_mod = "Error Structure",
    bias = "Bias",
    RMSPE = "RMSPE",
    fit = "Fit")) |>
  merge_v(part = "body", j = c(1:2)) |> 
  footnote(i = 1, j = 6,
           value = as_paragraph("Fit is R^2 for cyanobacteria models and AUC for microcystin models."), ref_symbols = "a", part = "header") |>
  theme_booktabs(bold_header = TRUE) |>
  fontsize(size = 10, part = "body") |>
  fontsize(size = 10, part = "header") |>
  fontsize(size = 9, part = "footer") |>
  theme_box() |>
  align(align = "center", part = "header")

```

```{r spatial covariance maps}
#| label: spcov-maps
#| fig-width: 6
#| fig-height: 6
#| fig-cap: "Spatial covariance for the cyanobacteria and microcystin models without in-lake data."

cyano_aug <- augment(cyano_nolake) |>
  mutate(spde = fitted(cyano_nolake, type = "spcov")$de,
         resp = "Cyanobacteria") |>
  select(resp, spde)

micx_aug <- augment(micx_nolake) |>
  mutate(spde = fitted(micx_nolake, type = "spcov")$de,
         resp = "Microcystin") |>
  select(resp, spde) |>
  st_transform(st_crs(cyano_aug))
  
spde <- rbind(cyano_aug, micx_aug)

ggplot() + 
  geom_sf(data = conus, fill = "#e2e2e2", color = "white", lwd = 1) +
  geom_sf(data = spde, 
          aes(fill = spde), pch = 21, size = 1.5) +
  facet_wrap(~ resp, ncol = 1, nrow = 2) +
  colorspace::scale_fill_continuous_divergingx(palette = "BrBG", 
                                               mid = 0, 
                                               name = "Spatial\nAutocorrelation") +
    theme_void()

```

## Supplemental Material

### Table of model variables

```{r construct variable summary table}
# Each variable that was considered in the modeling process
# Note that some of these values were excluded from the model development process because of suspected unreasonable outliers. Will need to update this once I determine where in the pipeline to trim these data.

summerizer <- function(var){
  colnum <- match(var[1], colnames(habs))
  dat    <- pull(habs, colnum)
  tibble(Variable = var[2],
         Units = var[3],
         Min = min(dat, na.rm = TRUE),
         Med = median(dat, na.rm = TRUE),
         Mean = mean(dat, na.rm = TRUE),
         Max = max(dat, na.rm = TRUE),
         Scale = var[4],
         Source = var[5]
         )
}

vec_list <- list(
  c("B_G_DENS", "Cyanobacteria", "cells/mL", "Lake", "NLA"),
  c("MICX", "Microcystin", "ug/L", "Lake", "NLA"),
  c("PTL", "Total Phosphorus", "ug/L", "Lake", "NLA"),
  c("NTL", "Total Nitrogen", "mg N/L", "Lake", "NLA"),
  c("NITRATE_N", "Nitrate", "mg N/L", "Lake", "NLA"),
  c("AMMONIA_N", "Ammonium", "mg N/L", "Lake", "NLA"),
  c("DOC", "Dissolved Organic Carbon", "mg/L", "Lake", "NLA"),
  c("PH", "pH", "Std. Units", "Lake", "NLA"),
  c("TURB", "Tubidty", "NTU", "Lake", "NLA"),
  c("EVAP_INFL", "Evaporation:Inflow", "unitless", "Lake", "NLA"),
  c("MAXDEPTH", "Maximum Lake Depth", "meters", "Lake", "NLA"),
  c("lakemorpho_fetch", "Lake Fetch", "meters", "Lake", "Lakemorpho"),
  c("N_Fert_Farm", "Farm Fertilizer N", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("N_livestock_Waste", "Livestock Waste N", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("N_CBNF", "Cultivated Crop Biological Nitrogen Fixation", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("P_f_fertilizer", "Farm Fertilizer P", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("P_livestock_Waste", "Livestock Waste P", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("N_Human_Waste", "Human Waste N", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("N_Fert_Urban", "Non-Farm Fertilizer N", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("P_human_waste_kg", "Human Waste P", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("P_nf_fertilizer", "Non-Farm Fertilizer P", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("n_farm_inputs", "Total Farm N Inputs", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
   c("p_farm_inputs", "Total Farm P Inputs", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
   c("n_dev_inputs", "Total Developed N Inputs", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
   c("p_dev_inputs", "Total Developed P Inputs", "kg/ha/yr", "Watershed", "National Nutrient Inventory"),
  c("fst_ws", "Forested Land Cover", "percent", "Watershed", "NLCD 2011"),
  c("BFIWs", "Baseflow Index", "unitless", "Watershed", "LakeCat"),
  c("precip_mean_month", "Month Mean Precipitation", "millimeters", "Watershed", "LakeCat"),
  c("temp_mean_month", "Month Mean Temperature", "degC", "Watershed", "LakeCat"),
  c("Precip8110Ws", "Mean Annual Precipitation", "millimeters", "Watershed", "LakeCat"),
  c("Tmean8110Ws", "Mean Annual Temperature", "millimeters", "Watershed", "LakeCat")
)

summary_covariate_table <- do.call(rbind, lapply(vec_list, summerizer)) |>
  mutate(Type = c(rep("In-Lake Conditions", 10), 
                  rep("Lake Geometry", 2), 
                  rep("Nutrient Inputs", 14), 
                  rep("Geographic Setting", 5)), .before = "Variable")

options(digits = 1)
covar_sum_table <- summary_covariate_table |>
  flextable() |>
  colformat_num(j = c("Min","Med","Mean","Max"), digits = 2, part = "body") |>
  merge_v(part = "body", j = 1) |> 
  theme_booktabs(bold_header = TRUE) |>
  theme_box() |>
  align(align = "center", part = "header") |>
  align(align = "center", j = 1, part = "body") |>
  fontsize(size = 10, part = "body") |>
  fontsize(size = 10, part = "header")

```

```{r varable summary table}
#| label: tbl-var-summary
#| tbl-cap: Summary statistics for response variable and covariates in the model.
covar_sum_table
```

```{r model selection tables}

# Create a table of model comparison process
tabs <- c("cyano_mod_compare_withlakedata.rds",
          "cyano_mod_compare_nolakedata.rds",
          "micx_iemod_compare_withlakedata.rds",
          "micx_iemod_compare_nolakedata.rds",
          "micx_spmod_compare_withlakedata.rds",
          "micx_spmod_compare_nolakedata.rds")

mod_comp_tabs <- lapply(tabs, function(tab){
  in_lake_conditions <- ifelse(grepl("withlakedata", tab), "Present", "Absent")
  error_structure    <- ifelse(grepl("cyano_mod", tab), "Spatial",
                               ifelse(grepl("iemod", tab), "Independent", "Spatial"))
  resp_var           <- ifelse(grepl("cyano", tab), "Cyanobacteria", "Microcystin")
  
  readRDS(paste0(here(), "./inst/model_objects/", tab)) |>
    mutate(resp_var = resp_var,
           error_structure = error_structure,
           inlake_conditions = in_lake_conditions, .before = 1) |>
    mutate(distinct_vars = gsub(", ", " \n", distinct_vars),
           common_vars = gsub(", ", " \n", common_vars))
})

# Combine cyanobacteria models
options(digits = 3)
cyano_mod_select <- rbind(mod_comp_tabs[[1]], mod_comp_tabs[[2]]) |>
  arrange(model) |>
  select(resp_var, error_structure, inlake_conditions, common_vars, distinct_vars, p, BIC, bias, RMSPE, cor2) |>
  mutate(inlake_conditions = factor(inlake_conditions, levels = c("Present", "Absent"))) |>
  arrange(inlake_conditions) |>
  mutate(common_vars = c(rep("Nitrate \nAmmonium \nDOC \npH \nTurbidity \nEvaporation/Inflow \nLake Depth \nLake Fetch", 6),
                         rep("Farm N Inputs \nDeveloped P Inputs \nBaseflow Index \nLake Depth \nLake Fetch", 6)),
         distinct_vars = c("Total N \nAnnual Precip \nAnnual Air Temp",
                           "Total P \nAnnual Precip \nAnnual Air Temp",
                           "Total N \nMonthly Precip \nMonthly Air Temp",
                           "Total N \nAnnual Precip \nAnnual Air Temp \nEcoregion",
                           "Total N \nAnnual Precip \nAnnual Air Temp \nTotal N * Lake Depth",
                           "Total N \nAnnual Precip \nAnnual Air Temp \nEcoregion \nTotal N * Ecoregion",
                           "Annual Precip \nAnnual Air Temp",
                           "Annual Precip \nAnnual Air Temp \nForest Cover",
                           "Monthly Precip \nMonthly Air Temp \nForest Cover",
                           "Annual Precip \nAnnual Air Temp \nForest Cover \nEcoregion",
                           "Annual Precip \nAnnual Air Temp \nForest Cover \nEcoregion \nFarm N Inputs * Lake Depth",
                           "Annual Precip \nAnnual Air Temp \nForest Cover \nEcoregion \nFarm N Inputs * Ecoregion"))

micx_iemod_select <- rbind(mod_comp_tabs[[3]], select(mod_comp_tabs[[4]], -bias, -MSPE, -RMSPE)) |>
  mutate(inlake_conditions = factor(inlake_conditions, levels = c("Present", "Absent"))) |>
  arrange(inlake_conditions, model) |>
  select(resp_var, error_structure, inlake_conditions, common_vars, distinct_vars, p, BIC, AUC) |>
  mutate(common_vars = c(rep("Nitrate \nDOC \nEvaporation/Inflow \nLake Depth \nLake Fetch", 6),
                         rep("Farm N Inputs \nDeveloped P Inputs \nBaseflow Index \nLake Depth \nLake Fetch", 6)),
         distinct_vars = c("Monthly Precip \nWater Temp",
                           "Annual Precip \nAnnual Air Temp",
                           "Annual Precip \nAnnual Air Temp \nNitrate",
                           "Annual Precip \nAnnual Air Temp \nNitrate \nFarm P Inputs",
                           "Annual Precip \nAnnual Air Temp \nNitrate \nFarm P Inputs \nEcoregion",
                           "Annual Precip \nAnnual Air Temp \nNitrate \nFarm P Inputs \nEcoregion \nTotal N * Lake Depth",
                           "Annual Precip \nAnnual Air Temp \nFarm N Inputs \nDeveloped P Inputs",
                           "Annual Precip \nAnnual Air Temp \nFarm P Inputs \nDeveloped N Inputs",
                           "Annual Precip \nAnnual Air Temp \nFarm P Inputs \nDeveloped N Inputs \nEcoregion",
                           "Monthly Precip \nMonthly Air Temp \nFarm P Inputs \nDeveloped N Inputs \nEcoregion",
                           "Annual Precip \nAnnual Air Temp \nFarm P Inputs \nDeveloped N Inputs \nForest Cover \nEcoregion",
                           "Annual Precip \nAnnual Air Temp \nFarm P Inputs \nDeveloped N Inputs \nForest Cover \nEcoregion \nFarm P Inputs * Ecoregion"))
  
micx_spmod_select <- rbind(mod_comp_tabs[[5]], mod_comp_tabs[[6]]) |>
  mutate(inlake_conditions = factor(inlake_conditions, levels = c("Present", "Absent"))) |>
  arrange(inlake_conditions, model) |>
  select(resp_var, error_structure, inlake_conditions, common_vars, distinct_vars, bias, RMSPE, AUC) |>
  mutate(common_vars = c(rep("Total N \nNitrate \nDOC \nEvaporation/Inflow \nLake Depth \nLake Fetch \nFarm P Inputs", 3),
                         rep("Farm P Inputs \nDeveloped N Inputs \nLake Depth \nLake Fetch \nAnnual Precip \nAnnual Air Temp \nBaseflow Index \nEcoregion", 3)),
         distinct_vars = c("",
                           "Ecoregion",
                           "Eocregion \nTotal N * Lake Depth",
                           "Ecoregion",
                           "Ecoregon \nForest Cover",
                           "Ecoregon \nForest Cover \nFarm P Inputs * Ecoregion"))

  

```

```{r cyano model selection table}
#| label: tbl-cyano-selection
#| tbl-cap: Summary statistics for response variable and covariates in the model.

cyano_header <- data.frame(
  col_keys = colnames(cyano_mod_select),
  line2 = c(rep("Model", 3), rep("Fixed Effects", 3),  "BIC", "Bias", "RMSPE", "R^2"),
  line3 = c("Response Variable", "Error Structure", "In-Lake Conditions", "Common", "Distinct", "Number", "BIC", "Bias", "RMSPE", "R^2")
)

cyano_mod_select |>
  flextable() |>
  set_header_df(mapping = cyano_header, key = "col_keys" ) |>
  merge_v(part = "header", j = c(7:10)) |> 
  merge_h(part = "header", i = 1) |>
  merge_v(part = "body", j = c(1:3)) |>
  theme_booktabs(bold_header = TRUE) |>
  fontsize(size = 10, part = "body") |>
  fontsize(size = 10, part = "header") |>
  theme_box() |>
  align(align = "center", part = "header")



```

